--[[-----------------------------------------]]
-- Analogue of engine quicksaves;
-- Use at your own risk!;
--[[-----------------------------------------]]

local quicksaves_count = 0

function save()
	if quicksaves_count > 10 then
	    quicksaves_count = 0
	end
	
	get_console():execute("save "..game.translate_string("st_quicksave").." - "..quicksaves_count)
	quicksaves_count = quicksaves_count + 1
end