@set allusersprofile=c:\programdata
@set appdata=c:\users\?????\appdata\roaming;C:\Users\ ¢¥«\AppData\Roaming
@set commandprompttype=native
@set commonprogramfiles=c:\program files\common files
@set commonprogramfiles(x86)=c:\program files (x86)\common files
@set commonprogramw6432=c:\program files\common files
@set complus_installroot=
@set complus_version=
@set computername=?????-??;€‚…‹-Š
@set comspec=c:\windows\system32\cmd.exe
@set devenvdir=c:\program files (x86)\microsoft visual studio\2017\community\common7\ide\
@set dxsdk_dir=c:\program files (x86)\microsoft directx sdk (august 2009)\
@set emergent_path=c:\emergent\gamebryo-lightspeed-3.2-source
@set extensionsdkdir=c:\program files (x86)\microsoft sdks\windows kits\10\extensionsdks
@set fp_no_host_check=no
@set framework40version=v4.0
@set frameworkdir=c:\windows\microsoft.net\framework64\
@set frameworkdir64=c:\windows\microsoft.net\framework64
@set frameworkversion=v4.0.30319
@set frameworkversion64=v4.0.30319
@set fsharpinstalldir=c:\program files (x86)\microsoft sdks\f#\10.1\framework\v4.0\
@set gtk_basepath=c:\program files (x86)\gtksharp\2.12\
@set homedrive=c:
@set homepath=\users\?????;\Users\ ¢¥«
@set include=c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.10.25017\atlmfc\include;c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.10.25017\include;c:\program files (x86)\windows kits\netfxsdk\4.6.1\include\um;c:\program files (x86)\windows kits\10\include\10.0.16299.0\ucrt;c:\program files (x86)\windows kits\10\include\10.0.16299.0\shared;c:\program files (x86)\windows kits\10\include\10.0.16299.0\um;c:\program files (x86)\windows kits\10\include\10.0.16299.0\winrt
@set lib=c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.10.25017\atlmfc\lib\x64;c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.10.25017\lib\x64;c:\program files (x86)\windows kits\netfxsdk\4.6.1\lib\um\x64;c:\program files (x86)\windows kits\10\lib\10.0.16299.0\ucrt\x64;c:\program files (x86)\windows kits\10\lib\10.0.16299.0\um\x64
@set libpath=c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.10.25017\atlmfc\lib\x64;c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.10.25017\lib\x64;c:\program files (x86)\windows kits\10\unionmetadata\10.0.16299.0\;c:\program files (x86)\windows kits\10\references\10.0.16299.0\;c:\windows\microsoft.net\framework64\v4.0.30319
@set localappdata=c:\users\?????\appdata\local;C:\Users\ ¢¥«\AppData\Local
@set logonserver=\\?????-??;\\€‚…‹-Š
@set moz_plugin_path=c:\program files (x86)\foxit software\foxit reader\plugins\
@set msbuildloadmicrosofttargetsreadonly=true
@set msbuildsdkspath=c:\program files (x86)\microsoft visual studio\2017\community\msbuild\sdks
@set msbuild_exe_path=c:\program files (x86)\pvs-studio\buildtools15\msbuild.exe
@set netfxsdkdir=c:\program files (x86)\windows kits\netfxsdk\4.6.1\
@set number_of_processors=4
@set os=windows_nt
@set path=c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.10.25017\bin\hostx64\x64;c:\program files (x86)\microsoft visual studio\2017\community\common7\ide\vc\vcpackages;c:\program files (x86)\microsoft sdks\typescript\2.2;c:\program files (x86)\microsoft visual studio\2017\community\common7\ide\commonextensions\microsoft\testwindow;c:\program files (x86)\microsoft visual studio\2017\community\common7\ide\commonextensions\microsoft\teamfoundation\team explorer;c:\program files (x86)\microsoft visual studio\2017\community\msbuild\15.0\bin\roslyn;c:\program files (x86)\microsoft visual studio\2017\community\team tools\performance tools;c:\program files (x86)\microsoft visual studio\shared\common\vsperfcollectiontools\;c:\program files (x86)\microsoft sdks\windows\v10.0a\bin\netfx 4.6.1 tools\;c:\program files (x86)\windows kits\10\bin\x64;c:\program files (x86)\windows kits\10\bin\10.0.16299.0\x64;c:\program files (x86)\microsoft visual studio\2017\community\\msbuild\15.0\bin;c:\windows\microsoft.net\framework64\v4.0.30319;c:\program files (x86)\microsoft visual studio\2017\community\common7\ide\;c:\program files (x86)\microsoft visual studio\2017\community\common7\tools\;c:\emergent\gamebryo-lightspeed-3.2-source\sdk\win32\dll;c:\program files (x86)\nvidia corporation\physx\common;c:\programdata\oracle\java\javapath;c:\program files (x86)\embarcadero\studio\18.0\bin;c:\users\public\documents\embarcadero\studio\18.0\bpl;c:\program files (x86)\embarcadero\studio\18.0\bin64;c:\users\public\documents\embarcadero\studio\18.0\bpl\win64;c:\progra~2\borland\cbuild~1\bin;c:\progra~2\borland\cbuild~1\projects\bpl;c:\program files (x86)\microsoft directx sdk (march 2008)\utilities\bin\x86;c:\windows\system32;c:\windows;c:\windows\system32\wbem;c:\windows\system32\windowspowershell\v1.0\;c:\program files (x86)\amd\ati.ace\core-static;c:\program files (x86)\microsoft sql server\90\tools\binn\;c:\program files (x86)\autodesk\backburner\;c:\program files\common files\autodesk shared\;c:\program files\microsoft sql server\110\tools\binn\;c:\program files\microsoft sql server\120\tools\binn\;c:\program files (x86)\gtksharp\2.12\bin;c:\program files\tortoisehg\;c:\program files\microsoft sql server\130\tools\binn\;c:\program files (x86)\skype\phone\;c:\program files\dotnet\;c:\program files (x86)\windows kits\8.1\windows performance toolkit\;%userprofile%\.dnx\bin;c:\program files\microsoft dnx\dnvm\;c:\program files (x86)\nodejs\;c:\program files\tortoisegit\bin;c:\program files\git\cmd;c:\users\?????\appdata\local\programs\python\python36-32\scripts\;c:\users\?????\appdata\local\programs\python\python36-32\;c:\mingw\bin\;c:\users\?????\appdata\roaming\npm;C:\Users\ ¢¥«\AppData\Local\Programs\Python\Python36-32\Scripts\;C:\Users\ ¢¥«\AppData\Local\Programs\Python\Python36-32\;C:\Users\ ¢¥«\AppData\Roaming\npm
@set pathext=.com;.exe;.bat;.cmd;.vbs;.vbe;.js;.jse;.wsf;.wsh;.msc
@set pkgdefapplicationconfigfile=c:\users\?????\appdata\local\microsoft\visualstudio\15.0_de10153b\devenv.exe.config;C:\Users\ ¢¥«\AppData\Local\Microsoft\VisualStudio\15.0_de10153b\devenv.exe.config
@set platform=x64
@set processor_architecture=amd64
@set processor_identifier=amd64 family 21 model 2 stepping 0, authenticamd
@set processor_level=21
@set processor_revision=0200
@set programdata=c:\programdata
@set programfiles=c:\program files
@set programfiles(x86)=c:\program files (x86)
@set programw6432=c:\program files
@set prompt=$p$g
@set psmodulepath=c:\windows\system32\windowspowershell\v1.0\modules\
@set public=c:\users\public
@set pvsbuildtoolsextensionspath=c:\program files (x86)\microsoft visual studio\2017\community\msbuild
@set pvs_vsinstalldir=c:\program files (x86)\microsoft visual studio\2017\community
@set qtmsbuild=c:\users\?????\appdata\local\qtmsbuild;C:\Users\ ¢¥«\AppData\Local\QtMsBuild
@set sessionname=console
@set sourcesdk=c:\program files (x86)\steam\steamapps\common\sourcesdk
@set systemdrive=c:
@set systemroot=c:\windows
@set temp=c:\users\7636~1\appdata\local\temp
@set tmp=c:\users\7636~1\appdata\local\temp
@set ucrtversion=10.0.16299.0
@set universalcrtsdkdir=c:\program files (x86)\windows kits\10\
@set userdomain=?????-??; ¢¥«-Š
@set username=?????; ¢¥«
@set userprofile=c:\users\?????;C:\Users\ ¢¥«
@set vcideinstalldir=c:\program files (x86)\microsoft visual studio\2017\community\common7\ide\vc\
@set vcinstalldir=c:\program files (x86)\microsoft visual studio\2017\community\vc\
@set vctoolsinstalldir=c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.10.25017\
@set vctoolsredistdir=c:\program files (x86)\microsoft visual studio\2017\community\vc\redist\msvc\14.10.25017\
@set visualstudiodir=c:\users\?????\documents\visual studio 2017;C:\Users\ ¢¥«\Documents\Visual Studio 2017
@set visualstudioedition=microsoft visual studio professional 2017
@set visualstudioversion=15.0
@set vproject=c:\program files (x86)\steam\steamapps\common\half-life 2\hl2
@set vs110comntools=c:\program files (x86)\microsoft visual studio 11.0\common7\tools\
@set vs120comntools=c:\program files (x86)\microsoft visual studio 12.0\common7\tools\
@set vs140comntools=c:\program files (x86)\microsoft visual studio 14.0\common7\tools\
@set vs150comntools=c:\program files (x86)\microsoft visual studio\2017\community\common7\tools\
@set vs80comntools=c:\program files (x86)\microsoft visual studio 8\common7\tools\
@set vsappiddir=c:\program files (x86)\microsoft visual studio\2017\professional\common7\ide\
@set vsappidname=devenv.exe
@set vscmd_arg_app_plat=desktop
@set vscmd_arg_host_arch=x64
@set vscmd_arg_tgt_arch=x64
@set vscmd_ver=15.0.26430.12
@set vsinstalldir=c:\program files (x86)\microsoft visual studio\2017\community\
@set vslang=1049
@set vssdk140install=c:\program files (x86)\microsoft visual studio 14.0\vssdk\
@set vssdk150install=c:\program files (x86)\microsoft visual studio\2017\community\vssdk
@set vsskuedition=professional
@set windir=c:\windows
@set windowslibpath=c:\program files (x86)\windows kits\10\unionmetadata\10.0.16299.0\;c:\program files (x86)\windows kits\10\references\10.0.16299.0\
@set windowssdkbinpath=c:\program files (x86)\windows kits\10\bin\
@set windowssdkdir=c:\program files (x86)\windows kits\10\
@set windowssdklibversion=10.0.16299.0\
@set windowssdkverbinpath=c:\program files (x86)\windows kits\10\bin\10.0.16299.0\
@set windowssdkversion=10.0.16299.0\
@set windowssdk_executablepath_x64=c:\program files (x86)\microsoft sdks\windows\v10.0a\bin\netfx 4.6.1 tools\x64\
@set windowssdk_executablepath_x86=c:\program files (x86)\microsoft sdks\windows\v10.0a\bin\netfx 4.6.1 tools\
@set windows_tracing_flags=3
@set windows_tracing_logfile=c:\bvtbin\tests\installpackage\csilogfile.log
@set __dotnet_add_64bit=1
@set __dotnet_preferred_bitness=64
@set __vscmd_preinit_path=c:\emergent\gamebryo-lightspeed-3.2-source\sdk\win32\dll;c:\program files (x86)\nvidia corporation\physx\common;c:\programdata\oracle\java\javapath;c:\program files (x86)\embarcadero\studio\18.0\bin;c:\users\public\documents\embarcadero\studio\18.0\bpl;c:\program files (x86)\embarcadero\studio\18.0\bin64;c:\users\public\documents\embarcadero\studio\18.0\bpl\win64;c:\progra~2\borland\cbuild~1\bin;c:\progra~2\borland\cbuild~1\projects\bpl;c:\program files (x86)\microsoft directx sdk (march 2008)\utilities\bin\x86;c:\windows\system32;c:\windows;c:\windows\system32\wbem;c:\windows\system32\windowspowershell\v1.0\;c:\program files (x86)\amd\ati.ace\core-static;c:\program files (x86)\microsoft sql server\90\tools\binn\;c:\program files (x86)\autodesk\backburner\;c:\program files\common files\autodesk shared\;c:\program files\microsoft sql server\110\tools\binn\;c:\program files\microsoft sql server\120\tools\binn\;c:\program files (x86)\gtksharp\2.12\bin;c:\program files\tortoisehg\;c:\program files\microsoft sql server\130\tools\binn\;c:\program files (x86)\skype\phone\;c:\program files\dotnet\;c:\program files (x86)\windows kits\8.1\windows performance toolkit\;%userprofile%\.dnx\bin;c:\program files\microsoft dnx\dnvm\;c:\program files (x86)\nodejs\;c:\program files\tortoisegit\bin;c:\program files\git\cmd;c:\users\?????\appdata\local\programs\python\python36-32\scripts\;c:\users\?????\appdata\local\programs\python\python36-32\;c:\mingw\bin\;c:\users\?????\appdata\roaming\npm

@call "C:\Program Files (x86)\PVS-Studio\x64\clang.exe" --driver-mode=cl @"C:\Games\Stalker\OxyGen\xray-oxygen\code\engine.vc2008\xrEngine\xrSkin2W_thread.cpp.PVS-Studio.preprocess.cmd.rsp" 2>&1