#pragma once

typedef	VkBlendFactor					D3D_BLEND;
typedef	VkBlendOp						D3D_BLEND_OP;
typedef	VkSamplerAddressMode			D3D_TEXTURE_ADDRESS_MODE;
typedef VkCompareOp						D3D_COMPARISON_FUNC;
typedef VkStencilOp						D3D_STENCIL_OP;
typedef VkCullModeFlags					D3D_CULL_MODE;
typedef	VkFilter						D3D_FILTER;

typedef VkSamplerCreateInfo						D3D_SAMPLER_DESC;
typedef VkPipelineRasterizationStateCreateInfo	D3D_RASTERIZER_DESC;
typedef VkPipelineDepthStencilStateCreateInfo	D3D_DEPTH_STENCIL_DESC;
typedef VkPipelineColorBlendStateCreateInfo		D3D_BLEND_DESC;

typedef VkDeviceMemory					D3D_SUBRESOURCE_DATA;

typedef	VkImageCreateInfo					D3D_TEXTURE1D_DESC;
typedef VkImageCreateInfo					D3D_TEXTURE2D_DESC;
typedef VkImageCreateInfo					D3D_TEXTURE3D_DESC;
typedef VkBufferCreateInfo					D3D_BUFFER_DESC;
typedef VkQueryPoolCreateInfo				D3D_QUERY_DESC;
typedef VkImageViewCreateInfo				D3D_SHADER_RESOURCE_VIEW_DESC;
typedef	VkImageViewCreateInfo				D3D_RENDER_TARGET_VIEW_DESC;
typedef	VkImageViewCreateInfo				D3D_DEPTH_STENCIL_VIEW_DESC;
typedef VkDeviceMemory						D3D_MAPPED_TEXTURE2D;
typedef VkDeviceMemory						D3D_MAPPED_TEXTURE3D;
typedef VkVertexInputAttributeDescription	D3D_INPUT_ELEMENT_DESC;
typedef VkPrimitiveTopology					D3D_PRIMITIVE_TOPOLOGY;
typedef	VkViewport							D3D_VIEWPORT;
typedef	VkImageUsageFlagBits				D3D_USAGE;

typedef VkPipeline								ID3DRasterizerState;
typedef VkPipeline								ID3DDepthStencilState;
typedef VkPipeline								ID3DBlendState;
typedef VkSampler								ID3DSamplerState;
typedef VkBuffer								ID3DBuffer;
typedef VkBuffer								ID3DVertexBuffer;
typedef VkBuffer								ID3DIndexBuffer;
typedef	VkPipeline								ID3DInputLayout;
typedef	VkShaderModule							ID3DVertexShader;
typedef	VkShaderModule							ID3DGeometryShader;
typedef	VkShaderModule							ID3DPixelShader;
typedef	VkImage									ID3DTexture1D;
typedef	VkImage									ID3DTexture2D;
typedef	VkImage									ID3DTexture3D;
typedef	VkImage									ID3DBaseTexture;
typedef VkImage									ID3DResource;
typedef	VkImageView								ID3DRenderTargetView;
typedef	VkImageView								ID3DDepthStencilView;
typedef	VkImageView								ID3DShaderResourceView;
typedef	VkQueryPool								ID3DQuery;
typedef	VkDevice								ID3DDevice;
typedef VkInstance								ID3DDeviceContext;

#include "vkState.h"

typedef	vkState									ID3DState;
#define D3D_COMMONSHADER_SAMPLER_SLOT_COUNT		( 16 )

//#define	D3D_REQ_TEXTURE2D_U_OR_V_DIMENSION		VK_REQ_TEXTURE2D_U_OR_V_DIMENSION

//#define	D3D_STANDARD_MULTISAMPLE_PATTERN		VK_STANDARD_MULTISAMPLE_PATTERN

//#define	D3D_DRIVER_TYPE_REFERENCE				VK_DRIVER_TYPE_REFERENCE
//#define	D3D_DRIVER_TYPE_HARDWARE				VK_DRIVER_TYPE_HARDWARE

//#define	D3D_PRIMITIVE_TOPOLOGY_UNDEFINED		VK_PRIMITIVE_TOPOLOGY_UNDEFINED
#define	D3D_PRIMITIVE_TOPOLOGY_POINTLIST		VK_PRIMITIVE_TOPOLOGY_POINT_LIST
#define	D3D_PRIMITIVE_TOPOLOGY_LINELIST			VK_PRIMITIVE_TOPOLOGY_LINE_LIST
#define	D3D_PRIMITIVE_TOPOLOGY_LINESTRIP		VK_PRIMITIVE_TOPOLOGY_LINE_STRIP
#define	D3D_PRIMITIVE_TOPOLOGY_TRIANGLELIST		VK_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST
#define	D3D_PRIMITIVE_TOPOLOGY_TRIANGLESTRIP	VK_PRIMITIVE_TOPOLOGY_TRIANGLE_STRIP
#define	D3D_PRIMITIVE_TOPOLOGY_TRIANGLEFAN		VK_PRIMITIVE_TOPOLOGY_TRIANGLE_FAN

#define	D3D_USAGE_DEFAULT		VK_IMAGE_LAYOUT_UNDEFINED
#define	D3D_USAGE_DYNAMIC		VK_IMAGE_LAYOUT_GENERAL
//#define	D3D_USAGE_STAGING		VK_USAGE_STAGING
#define	D3D_USAGE_IMMUTABLE		VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL

#define	D3D_CULL_NONE		VK_CULL_MODE_NONE
#define	D3D_CULL_FRONT		VK_CULL_MODE_FRONT_BIT
#define	D3D_CULL_BACK		VK_CULL_MODE_BACK_BIT

#define	D3D_COMPARISON_NEVER			VK_COMPARE_OP_NEVER
#define	D3D_COMPARISON_LESS				VK_COMPARE_OP_LESS
#define	D3D_COMPARISON_EQUAL			VK_COMPARE_OP_EQUAL
#define	D3D_COMPARISON_LESS_EQUAL		VK_COMPARE_OP_LESS_OR_EQUAL
#define	D3D_COMPARISON_GREATER			VK_COMPARE_OP_GREATER
#define	D3D_COMPARISON_NOT_EQUAL		VK_COMPARE_OP_NOT_EQUAL
#define	D3D_COMPARISON_GREATER_EQUAL	VK_COMPARE_OP_GREATER_OR_EQUAL
#define	D3D_COMPARISON_ALWAYS			VK_COMPARE_OP_ALWAYS

#define	D3D_STENCIL_OP_KEEP			VK_STENCIL_OP_KEEP
#define	D3D_STENCIL_OP_ZERO			VK_STENCIL_OP_ZERO
#define	D3D_STENCIL_OP_REPLACE		VK_STENCIL_OP_REPLACE
#define	D3D_STENCIL_OP_INCR_SAT		VK_STENCIL_OP_INCREMENT_AND_CLAMP
#define	D3D_STENCIL_OP_DECR_SAT		VK_STENCIL_OP_DECREMENT_AND_CLAMP
#define	D3D_STENCIL_OP_INVERT		VK_STENCIL_OP_INVERT
#define	D3D_STENCIL_OP_INCR			VK_STENCIL_OP_INCREMENT_AND_WRAP
#define	D3D_STENCIL_OP_DECR			VK_STENCIL_OP_DECREMENT_AND_WRAP

#define	D3D_BLEND_ZERO					VK_BLEND_FACTOR_ZERO
#define	D3D_BLEND_ONE					VK_BLEND_FACTOR_ONE
#define	D3D_BLEND_SRC_COLOR				VK_BLEND_FACTOR_SRC_COLOR
#define	D3D_BLEND_INV_SRC_COLOR			VK_BLEND_FACTOR_ONE_MINUS_SRC_COLOR
#define	D3D_BLEND_SRC_ALPHA				VK_BLEND_FACTOR_SRC_ALPHA
#define	D3D_BLEND_INV_SRC_ALPHA			VK_BLEND_FACTOR_ONE_MINUS_SRC_ALPHA
#define	D3D_BLEND_DEST_ALPHA			VK_BLEND_FACTOR_DST_ALPHA
#define	D3D_BLEND_INV_DEST_ALPHA		VK_BLEND_FACTOR_ONE_MINUS_DST_ALPHA
#define	D3D_BLEND_DEST_COLOR			VK_BLEND_FACTOR_DST_COLOR
#define	D3D_BLEND_INV_DEST_COLOR		VK_BLEND_FACTOR_ONE_MINUS_DST_COLOR
#define	D3D_BLEND_SRC_ALPHA_SAT			VK_BLEND_FACTOR_SRC_ALPHA_SATURATE
#define	D3D_BLEND_BLEND_FACTOR			VK_BLEND_FACTOR_CONSTANT_COLOR
#define	D3D_BLEND_INV_BLEND_FACTOR		VK_BLEND_FACTOR_ONE_MINUS_CONSTANT_COLOR
#define	D3D_BLEND_SRC1_COLOR			VK_BLEND_FACTOR_SRC1_COLOR
#define	D3D_BLEND_INV_SRC1_COLOR		VK_BLEND_FACTOR_ONE_MINUS_SRC1_COLOR
#define	D3D_BLEND_SRC1_ALPHA			VK_BLEND_FACTOR_SRC1_ALPHA
#define	D3D_BLEND_INV_SRC1_ALPHA		VK_BLEND_FACTOR_ONE_MINUS_SRC1_ALPHA

#define	D3D_BLEND_OP_ADD				VK_BLEND_OP_ADD
#define	D3D_BLEND_OP_SUBTRACT			VK_BLEND_OP_SUBTRACT
#define	D3D_BLEND_OP_REV_SUBTRACT		VK_BLEND_OP_REVERSE_SUBTRACT
#define	D3D_BLEND_OP_MIN				VK_BLEND_OP_MIN
#define	D3D_BLEND_OP_MAX				VK_BLEND_OP_MAX

#define	D3D_TEXTURE_ADDRESS_WRAP		VK_SAMPLER_ADDRESS_MODE_REPEAT
#define	D3D_TEXTURE_ADDRESS_MIRROR		VK_SAMPLER_ADDRESS_MODE_MIRRORED_REPEAT
#define	D3D_TEXTURE_ADDRESS_CLAMP		VK_SAMPLER_ADDRESS_MODE_CLAMP_TO_EDGE
#define	D3D_TEXTURE_ADDRESS_BORDER		VK_SAMPLER_ADDRESS_MODE_CLAMP_TO_BORDER
#define	D3D_TEXTURE_ADDRESS_MIRROR_ONCE	VK_SAMPLER_ADDRESS_MODE_MIRROR_CLAMP_TO_EDGE

#define	D3D_DEPTH_WRITE_MASK_ALL		VK_TRUE
#define	D3D_DEPTH_WRITE_MASK_ZERO		VK_FALSE
#define	D3D_COLOR_WRITE_ENABLE_ALL		VK_COLOR_COMPONENT_R_BIT | VK_COLOR_COMPONENT_G_BIT | VK_COLOR_COMPONENT_B_BIT | VK_COLOR_COMPONENT_A_BIT

#define	D3D_FILTER_ANISOTROPIC				VK_FILTER_LINEAR
#define	D3D_FILTER_MIN_MAG_MIP_LINEAR		VK_FILTER_LINEAR
#define	D3D_FILTER_COMPARISON_ANISOTROPIC	VK_FILTER_LINEAR

#define	D3D_FILL_SOLID		VK_POLYGON_MODE_FILL
#define	D3D_FILL_WIREFRAME	VK_POLYGON_MODE_LINE

//#define	D3D_INPUT_PER_VERTEX_DATA	VK_INPUT_PER_VERTEX_DATA

#define	D3D_BIND_INDEX_BUFFER			VK_BUFFER_USAGE_INDEX_BUFFER_BIT
#define	D3D_BIND_VERTEX_BUFFER			VK_BUFFER_USAGE_VERTEX_BUFFER_BIT
#define	D3D_BIND_CONSTANT_BUFFER		VK_BUFFER_USAGE_UNIFORM_BUFFER_BIT
#define	D3D_BIND_SHADER_RESOURCE		VK_IMAGE_USAGE_SAMPLED_BIT
#define	D3D_BIND_DEPTH_STENCIL			VK_IMAGE_USAGE_DEPTH_STENCIL_ATTACHMENT_BIT
//#define	D3D_BIND_STREAM_OUTPUT			VK_BUFFER_STREAM_OUTPUT
#define	D3D_BIND_RENDER_TARGET			VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT
#define	D3D_BIND_DEPTH_STENCIL			VK_IMAGE_USAGE_DEPTH_STENCIL_ATTACHMENT_BIT
//#define	D3D_BIND_UNORDERED_ACCESS		VK_BUFFER_UNORDERED_ACCESS

#define	D3D_CPU_ACCESS_WRITE		VK_ACCESS_HOST_WRITE_BIT
#define	D3D_CPU_ACCESS_READ			VK_ACCESS_HOST_READ_BIT

//#define	D3D_MAP_READ					VK_MAP_READ
//#define	D3D_MAP_WRITE					VK_MAP_WRITE
//#define	D3D_MAP_READ_WRITE				VK_MAP_READ_WRITE
//#define	D3D_MAP_WRITE_DISCARD			VK_MAP_WRITE_DISCARD
//#define	D3D_MAP_WRITE_NO_OVERWRITE		VK_MAP_WRITE_NO_OVERWRITE
//typedef	VK_MAP	D3D_MAP;

//#define	D3D_RESOURCE_MISC_GENERATE_MIPS				VK_RESOURCE_MISC_GENERATE_MIPS
//#define	D3D_RESOURCE_MISC_SHARED					VK_RESOURCE_MISC_SHARED
//#define	D3D_RESOURCE_MISC_TEXTURECUBE				VK_RESOURCE_MISC_TEXTURECUBE
//#define	D3D_RESOURCE_MISC_DRAWINDIRECT_ARGS			VK_RESOURCE_MISC_DRAWINDIRECT_ARGS
//#define	D3D_RESOURCE_MISC_BUFFER_ALLOW_RAW_VIEWS	VK_RESOURCE_MISC_BUFFER_ALLOW_RAW_VIEWS
//#define	D3D_RESOURCE_MISC_BUFFER_STRUCTURED			VK_RESOURCE_MISC_BUFFER_STRUCTURED
//#define	D3D_RESOURCE_MISC_RESOURCE_CLAMP			VK_RESOURCE_MISC_RESOURCE_CLAMP
//#define	D3D_RESOURCE_MISC_SHARED_KEYEDMUTEX			VK_RESOURCE_MISC_SHARED_KEYEDMUTEX
//#define	D3D_RESOURCE_MISC_GDI_COMPATIBLE			VK_RESOURCE_MISC_GDI_COMPATIBLE

//#define	D3D_CLEAR_DEPTH		VK_CLEAR_DEPTH
//#define	D3D_CLEAR_STENCIL	VK_CLEAR_STENCIL

//#define	D3D_QUERY_EVENT							VK_QUERY_TYPE_EVENT
#define	D3D_QUERY_OCCLUSION						VK_QUERY_TYPE_OCCLUSION
#define	D3D_QUERY_TIMESTAMP						VK_QUERY_TYPE_TIMESTAMP
//#define	D3D_QUERY_TIMESTAMP_DISJOINT			VK_QUERY_TYPE_TIMESTAMP_DISJOINT
#define	D3D_QUERY_PIPELINE_STATISTICS			VK_QUERY_TYPE_PIPELINE_STATISTICS
//#define	D3D_QUERY_OCCLUSION_PREDICATE			VK_QUERY_TYPE_OCCLUSION_PREDICATE
//#define	D3D_QUERY_SO_STATISTICS					VK_QUERY_TYPE_SO_STATISTICS
//#define	D3D_QUERY_SO_OVERFLOW_PREDICATE			VK_QUERY_TYPE_SO_OVERFLOW_PREDICATE
//#define	D3D_QUERY_SO_STATISTICS_STREAM0			VK_QUERY_TYPE_SO_STATISTICS_STREAM0
//#define	D3D_QUERY_SO_OVERFLOW_PREDICATE_STREAM0	VK_QUERY_TYPE_SO_OVERFLOW_PREDICATE_STREAM0
//#define	D3D_QUERY_SO_STATISTICS_STREAM1			VK_QUERY_TYPE_SO_STATISTICS_STREAM1
//#define	D3D_QUERY_SO_OVERFLOW_PREDICATE_STREAM1	VK_QUERY_TYPE_SO_OVERFLOW_PREDICATE_STREAM1
//#define	D3D_QUERY_SO_STATISTICS_STREAM2			VK_QUERY_TYPE_SO_STATISTICS_STREAM2
//#define	D3D_QUERY_SO_OVERFLOW_PREDICATE_STREAM2	VK_QUERY_TYPE_SO_OVERFLOW_PREDICATE_STREAM2
//#define	D3D_QUERY_SO_STATISTICS_STREAM3			VK_QUERY_TYPE_SO_STATISTICS_STREAM3
//#define	D3D_QUERY_SO_OVERFLOW_PREDICATE_STREAM3	VK_QUERY_TYPE_SO_OVERFLOW_PREDICATE_STREAM3

//#define	D3D_RESOURCE_DIMENSION_UNKNOWN			VK_RESOURCE_DIMENSION_UNKNOWN
//#define	D3D_RESOURCE_DIMENSION_BUFFER			VK_RESOURCE_DIMENSION_BUFFER
#define	D3D_RESOURCE_DIMENSION_TEXTURE1D		VK_IMAGE_TYPE_1D
#define	D3D_RESOURCE_DIMENSION_TEXTURE2D		VK_IMAGE_TYPE_2D
#define	D3D_RESOURCE_DIMENSION_TEXTURE3D		VK_IMAGE_TYPE_3D
typedef VkImageType	D3D_RESOURCE_DIMENSION;

//#define	D3D_SRV_DIMENSION_UNKNOWN				VK_SRV_DIMENSION_UNKNOWN
//#define	D3D_SRV_DIMENSION_BUFFER				VK_SRV_DIMENSION_BUFFER
#define	D3D_SRV_DIMENSION_TEXTURE1D				VK_IMAGE_VIEW_TYPE_1D
#define	D3D_SRV_DIMENSION_TEXTURE1DARRAY		VK_IMAGE_VIEW_TYPE_1D_ARRAY
#define	D3D_SRV_DIMENSION_TEXTURE2D				VK_IMAGE_VIEW_TYPE_2D
#define	D3D_SRV_DIMENSION_TEXTURE2DARRAY		VK_IMAGE_VIEW_TYPE_2D_ARRAY
#define	D3D_SRV_DIMENSION_TEXTURE2DMS			VK_IMAGE_VIEW_TYPE_2D
#define	D3D_SRV_DIMENSION_TEXTURE2DMSARRAY		VK_IMAGE_VIEW_TYPE_2D_ARRAY
#define	D3D_SRV_DIMENSION_TEXTURE3D				VK_IMAGE_VIEW_TYPE_3D
#define	D3D_SRV_DIMENSION_TEXTURECUBE			VK_IMAGE_VIEW_TYPE_CUBE
#define	D3D_SRV_DIMENSION_TEXTURECUBEARRAY		VK_IMAGE_VIEW_TYPE_CUBE_ARRAY
//#define	D3D_SRV_DIMENSION_BUFFEREX				VK_SRV_DIMENSION_BUFFEREX

//#define	D3D_DSV_DIMENSION_UNKNOWN				VK_DSV_DIMENSION_UNKNOWN
#define	D3D_DSV_DIMENSION_TEXTURE1D				VK_IMAGE_VIEW_TYPE_1D
#define	D3D_DSV_DIMENSION_TEXTURE1DARRAY		VK_IMAGE_VIEW_TYPE_1D_ARRAY
#define	D3D_DSV_DIMENSION_TEXTURE2D				VK_IMAGE_VIEW_TYPE_2D
#define	D3D_DSV_DIMENSION_TEXTURE2DARRAY		VK_IMAGE_VIEW_TYPE_2D_ARRAY
#define	D3D_DSV_DIMENSION_TEXTURE2DMS			VK_IMAGE_VIEW_TYPE_2D
#define	D3D_DSV_DIMENSION_TEXTURE2DMSARRAY		VK_IMAGE_VIEW_TYPE_2D_ARRAY

//#define	D3D_RTV_DIMENSION_UNKNOWN				VK_RTV_DIMENSION_UNKNOWN
//#define	D3D_RTV_DIMENSION_BUFFER				VK_RTV_DIMENSION_BUFFER
#define	D3D_RTV_DIMENSION_TEXTURE1D				VK_IMAGE_VIEW_TYPE_1D
#define	D3D_RTV_DIMENSION_TEXTURE1DARRAY		VK_IMAGE_VIEW_TYPE_1D_ARRAY
#define	D3D_RTV_DIMENSION_TEXTURE2D				VK_IMAGE_VIEW_TYPE_2D
#define	D3D_RTV_DIMENSION_TEXTURE2DARRAY		VK_IMAGE_VIEW_TYPE_2D_ARRAY
#define	D3D_RTV_DIMENSION_TEXTURE2DMS			VK_IMAGE_VIEW_TYPE_2D
#define	D3D_RTV_DIMENSION_TEXTURE2DMSARRAY		VK_IMAGE_VIEW_TYPE_2D_ARRAY
#define	D3D_RTV_DIMENSION_TEXTURE3D				VK_IMAGE_VIEW_TYPE_3D

//#define	D3D_UAV_DIMENSION_UNKNOWN				VK_UAV_DIMENSION_UNKNOWN
//#define	D3D_UAV_DIMENSION_BUFFER				VK_UAV_DIMENSION_BUFFER
#define	D3D_UAV_DIMENSION_TEXTURE1D				VK_IMAGE_VIEW_TYPE_1D
#define	D3D_UAV_DIMENSION_TEXTURE1DARRAY		VK_IMAGE_VIEW_TYPE_1D_ARRAY
#define	D3D_UAV_DIMENSION_TEXTURE2D				VK_IMAGE_VIEW_TYPE_2D
#define	D3D_UAV_DIMENSION_TEXTURE2DARRAY		VK_IMAGE_VIEW_TYPE_2D_ARRAY
#define	D3D_UAV_DIMENSION_TEXTURE3D				VK_IMAGE_VIEW_TYPE_3D

// TODO: Implement Vulkan glslang shader reflection
//typedef	VK_SHADER_DESC				D3D_SHADER_DESC;
//typedef	VK_SHADER_BUFFER_DESC		D3D_SHADER_BUFFER_DESC;
//typedef	VK_SHADER_VARIABLE_DESC		D3D_SHADER_VARIABLE_DESC;
//typedef	VK_SHADER_INPUT_BIND_DESC	D3D_SHADER_INPUT_BIND_DESC;
//typedef	VK_SHADER_TYPE_DESC			D3D_SHADER_TYPE_DESC;
//typedef	VK_CBUFFER_TYPE				D3D_CBUFFER_TYPE;

//typedef	ID3D11ShaderReflection							ID3DShaderReflection;
//typedef	ID3D11ShaderReflectionConstantBuffer			ID3DShaderReflectionConstantBuffer;
//typedef	ID3D11ShaderReflectionVariable					ID3DShaderReflectionVariable;
//typedef	ID3D11ShaderReflectionType						ID3DShaderReflectionType;


//#define	IID_ID3DShaderReflection	IID_ID3D11ShaderReflection